### ISSUE TITLE
document that stellar network needs to be set

### ISSUE THREAD

**Issue by dgobaud** [astroband/ruby-stellar-sdk#13] opened 2018-01-09 14:16 UTC
Stellar::Client.default.create_account signs things with testnet

**Comment by ramontayag** [comment] 2018-01-10 00:36
Pull requests are welcome :)

**Comment by nullstyle** [comment] 2018-07-10 22:22
duplicate of #22 

I'm closing this issue since the other has been edited to reflect my planned changes to solve this issue.

**Closed as completed by nullstyle** 2018-07-10 22:22 UTC
